server:
  port: 8013

spring:
  # 默认是点对点的配置
  activemq:
    # activemq url
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
      enabled: false
#  # 修改默认消费类型，默认是点对点，这里如果是false，则为点对点，否则是订阅，
#  # 但是，这种也是写死的方式，不能灵活配置，最好的方式是定义一个工厂
#  jms:
#    pub-sub-domain: true