server:
  port: 8015

datasource:
  url: localhost:3306/shiro_springboot

spring:
  datasource:
    url: jdbc:mysql://${datasource.url}?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf-8 # 连不上的话十有八九就是这里
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari: # 自带的高性能数据库连接池
      maximum-pool-size: 10
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.yjiewei.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范，比如user_name能够匹配实体的userName
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml